# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  db:
    env_file:
      - "./api/.env"
    image: mysql
  api:
    env_file:
      - "./api/.env"
    image: docker.io/bitnami/laravel:latest
    ports:
      - '8000:8000'
    volumes:
      - './api:/app'
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
